<<<<<<< HEAD
// STM32F103C8T6 LQFP48 芯片专属引脚数据
// 该文件仅包含当前芯片的数据定义，方便后续按型号拆分和维护
const pinData = [
    { num: 1, name: 'VBAT', type: 'power', desc: '备份电源输入', alt: '为RTC和备份寄存器供电' },
    { num: 2, name: 'PC13', type: 'gpio', desc: '通用I/O PC13', alt: '侵入检测 / RTC输出' },
    { num: 3, name: 'PC14', type: 'clock', desc: '通用I/O PC14', alt: '32.768kHz晶振输入 (OSC32_IN)' },
    { num: 4, name: 'PC15', type: 'clock', desc: '通用I/O PC15', alt: '32.768kHz晶振输出 (OSC32_OUT)' },
    { num: 5, name: 'PD0', type: 'clock', desc: '通用I/O PD0', alt: '主晶振输入 (OSC_IN)' },
    { num: 6, name: 'PD1', type: 'clock', desc: '通用I/O PD1', alt: '主晶振输出 (OSC_OUT)' },
    { num: 7, name: 'NRST', type: 'reset', desc: '系统复位引脚', alt: '低电平复位，内置上拉电阻' },
    { num: 8, name: 'VSSA', type: 'power', desc: '模拟地', alt: 'ADC/DAC模拟电路接地' },
    { num: 9, name: 'VDDA', type: 'power', desc: '模拟电源 (2.0~3.6V)', alt: '为ADC/DAC/复位电路供电' },
    { num: 10, name: 'PA0', type: 'analog', desc: '通用I/O PA0', alt: 'ADC12_IN0 / 唤醒引脚 / TIM2_CH1' },
    { num: 11, name: 'PA1', type: 'analog', desc: '通用I/O PA1', alt: 'ADC12_IN1 / TIM2_CH2' },
    { num: 12, name: 'PA2', type: 'analog', desc: '通用I/O PA2', alt: 'ADC12_IN2 / USART2_TX / TIM2_CH3' },
    { num: 13, name: 'PA3', type: 'analog', desc: '通用I/O PA3', alt: 'ADC12_IN3 / USART2_RX / TIM2_CH4' },
    { num: 14, name: 'PA4', type: 'analog', desc: '通用I/O PA4', alt: 'ADC12_IN4 / SPI1_NSS / USART2_CK' },
    { num: 15, name: 'PA5', type: 'analog', desc: '通用I/O PA5', alt: 'ADC12_IN5 / SPI1_SCK' },
    { num: 16, name: 'PA6', type: 'analog', desc: '通用I/O PA6', alt: 'ADC12_IN6 / SPI1_MISO / TIM3_CH1' },
    { num: 17, name: 'PA7', type: 'analog', desc: '通用I/O PA7', alt: 'ADC12_IN7 / SPI1_MOSI / TIM3_CH2' },
    { num: 18, name: 'PB0', type: 'analog', desc: '通用I/O PB0', alt: 'ADC12_IN8 / TIM3_CH3' },
    { num: 19, name: 'PB1', type: 'analog', desc: '通用I/O PB1', alt: 'ADC12_IN9 / TIM3_CH4' },
    { num: 20, name: 'PB2', type: 'boot', desc: '通用I/O PB2 / BOOT1', alt: '启动模式选择引脚1' },
    { num: 21, name: 'PB10', type: 'gpio', desc: '通用I/O PB10', alt: 'I2C2_SCL / USART3_TX / TIM2_CH3' },
    { num: 22, name: 'PB11', type: 'gpio', desc: '通用I/O PB11', alt: 'I2C2_SDA / USART3_RX / TIM2_CH4' },
    { num: 23, name: 'VSS_1', type: 'power', desc: '数字地 (I/O接地)', alt: '主数字电路接地引脚1' },
    { num: 24, name: 'VDD_1', type: 'power', desc: '数字电源 (2.0~3.6V)', alt: '主数字电路供电引脚1' },
    { num: 25, name: 'PB12', type: 'gpio', desc: '通用I/O PB12', alt: 'SPI2_NSS / I2C2_SMBA / USART3_CK' },
    { num: 26, name: 'PB13', type: 'gpio', desc: '通用I/O PB13', alt: 'SPI2_SCK / USART3_CTS / TIM1_CH1N' },
    { num: 27, name: 'PB14', type: 'gpio', desc: '通用I/O PB14', alt: 'SPI2_MISO / USART3_RTS / TIM1_CH2N' },
    { num: 28, name: 'PB15', type: 'gpio', desc: '通用I/O PB15', alt: 'SPI2_MOSI / TIM1_CH3N' },
    { num: 29, name: 'PA8', type: 'gpio', desc: '通用I/O PA8', alt: 'USART1_CK / TIM1_CH1 / MCO时钟输出' },
    { num: 30, name: 'PA9', type: 'gpio', desc: '通用I/O PA9', alt: 'USART1_TX / TIM1_CH2' },
    { num: 31, name: 'PA10', type: 'gpio', desc: '通用I/O PA10', alt: 'USART1_RX / TIM1_CH3' },
    { num: 32, name: 'PA11', type: 'gpio', desc: '通用I/O PA11', alt: 'USART1_CTS / CAN_RX / TIM1_CH4' },
    { num: 33, name: 'PA12', type: 'gpio', desc: '通用I/O PA12', alt: 'USART1_RTS / CAN_TX / TIM1_ETR' },
    { num: 34, name: 'PA13', type: 'jtag', desc: 'JTAG/SWD调试接口', alt: 'JTMS-SWDIO / 通用I/O PA13' },
    { num: 35, name: 'VSS_2', type: 'power', desc: '数字地 (I/O接地)', alt: '主数字电路接地引脚2' },
    { num: 36, name: 'VDD_2', type: 'power', desc: '数字电源 (2.0~3.6V)', alt: '主数字电路供电引脚2' },
    { num: 37, name: 'PA14', type: 'jtag', desc: 'JTAG/SWD调试接口', alt: 'JTCK-SWCLK / 通用I/O PA14' },
    { num: 38, name: 'PA15', type: 'jtag', desc: 'JTAG调试接口', alt: 'JTDI / 通用I/O PA15 / TIM2_CH1' },
    { num: 39, name: 'PB3', type: 'jtag', desc: 'JTAG调试接口', alt: 'JTDO / 通用I/O PB3 / TIM2_CH2' },
    { num: 40, name: 'PB4', type: 'jtag', desc: 'JTAG调试接口', alt: 'JNTRST / 通用I/O PB4 / TIM3_CH1' },
    { num: 41, name: 'PB5', type: 'gpio', desc: '通用I/O PB5', alt: 'I2C1_SMBA / TIM3_CH2' },
    { num: 42, name: 'PB6', type: 'gpio', desc: '通用I/O PB6', alt: 'I2C1_SCL / TIM4_CH1 / USART1_TX(重映射)' },
    { num: 43, name: 'PB7', type: 'gpio', desc: '通用I/O PB7', alt: 'I2C1_SDA / TIM4_CH2 / USART1_RX(重映射)' },
    { num: 44, name: 'BOOT0', type: 'boot', desc: '启动模式选择引脚0', alt: '高电平进入系统存储器Bootloader' },
    { num: 45, name: 'PB8', type: 'gpio', desc: '通用I/O PB8', alt: 'TIM4_CH3 / I2C1_SCL(重映射) / CAN_RX(重映射)' },
    { num: 46, name: 'PB9', type: 'gpio', desc: '通用I/O PB9', alt: 'TIM4_CH4 / I2C1_SDA(重映射) / CAN_TX(重映射)' },
    { num: 47, name: 'VSS_3', type: 'power', desc: '数字地 (I/O接地)', alt: '主数字电路接地引脚3' },
    { num: 48, name: 'VDD_3', type: 'power', desc: '数字电源 (2.0~3.6V)', alt: '主数字电路供电引脚3' },
];
=======
// STM32F103C8T6 LQFP48 芯片专属引脚数据
// 该文件仅包含当前芯片的数据定义，方便后续按型号拆分和维护
const pinData = [
    { num: 1, name: 'VBAT', type: 'power', desc: '备份电源输入', alt: '为RTC和备份寄存器供电' },
    { num: 2, name: 'PC13', type: 'gpio', desc: '通用I/O PC13', alt: '侵入检测 / RTC输出' },
    { num: 3, name: 'PC14', type: 'clock', desc: '通用I/O PC14', alt: '32.768kHz晶振输入 (OSC32_IN)' },
    { num: 4, name: 'PC15', type: 'clock', desc: '通用I/O PC15', alt: '32.768kHz晶振输出 (OSC32_OUT)' },
    { num: 5, name: 'PD0', type: 'clock', desc: '通用I/O PD0', alt: '主晶振输入 (OSC_IN)' },
    { num: 6, name: 'PD1', type: 'clock', desc: '通用I/O PD1', alt: '主晶振输出 (OSC_OUT)' },
    { num: 7, name: 'NRST', type: 'reset', desc: '系统复位引脚', alt: '低电平复位，内置上拉电阻' },
    { num: 8, name: 'VSSA', type: 'power', desc: '模拟地', alt: 'ADC/DAC模拟电路接地' },
    { num: 9, name: 'VDDA', type: 'power', desc: '模拟电源 (2.0~3.6V)', alt: '为ADC/DAC/复位电路供电' },
    { num: 10, name: 'PA0', type: 'analog', desc: '通用I/O PA0', alt: 'ADC12_IN0 / 唤醒引脚 / TIM2_CH1' },
    { num: 11, name: 'PA1', type: 'analog', desc: '通用I/O PA1', alt: 'ADC12_IN1 / TIM2_CH2' },
    { num: 12, name: 'PA2', type: 'analog', desc: '通用I/O PA2', alt: 'ADC12_IN2 / USART2_TX / TIM2_CH3' },
    { num: 13, name: 'PA3', type: 'analog', desc: '通用I/O PA3', alt: 'ADC12_IN3 / USART2_RX / TIM2_CH4' },
    { num: 14, name: 'PA4', type: 'analog', desc: '通用I/O PA4', alt: 'ADC12_IN4 / SPI1_NSS / USART2_CK' },
    { num: 15, name: 'PA5', type: 'analog', desc: '通用I/O PA5', alt: 'ADC12_IN5 / SPI1_SCK' },
    { num: 16, name: 'PA6', type: 'analog', desc: '通用I/O PA6', alt: 'ADC12_IN6 / SPI1_MISO / TIM3_CH1' },
    { num: 17, name: 'PA7', type: 'analog', desc: '通用I/O PA7', alt: 'ADC12_IN7 / SPI1_MOSI / TIM3_CH2' },
    { num: 18, name: 'PB0', type: 'analog', desc: '通用I/O PB0', alt: 'ADC12_IN8 / TIM3_CH3' },
    { num: 19, name: 'PB1', type: 'analog', desc: '通用I/O PB1', alt: 'ADC12_IN9 / TIM3_CH4' },
    { num: 20, name: 'PB2', type: 'boot', desc: '通用I/O PB2 / BOOT1', alt: '启动模式选择引脚1' },
    { num: 21, name: 'PB10', type: 'gpio', desc: '通用I/O PB10', alt: 'I2C2_SCL / USART3_TX / TIM2_CH3' },
    { num: 22, name: 'PB11', type: 'gpio', desc: '通用I/O PB11', alt: 'I2C2_SDA / USART3_RX / TIM2_CH4' },
    { num: 23, name: 'VSS_1', type: 'power', desc: '数字地 (I/O接地)', alt: '主数字电路接地引脚1' },
    { num: 24, name: 'VDD_1', type: 'power', desc: '数字电源 (2.0~3.6V)', alt: '主数字电路供电引脚1' },
    { num: 25, name: 'PB12', type: 'gpio', desc: '通用I/O PB12', alt: 'SPI2_NSS / I2C2_SMBA / USART3_CK' },
    { num: 26, name: 'PB13', type: 'gpio', desc: '通用I/O PB13', alt: 'SPI2_SCK / USART3_CTS / TIM1_CH1N' },
    { num: 27, name: 'PB14', type: 'gpio', desc: '通用I/O PB14', alt: 'SPI2_MISO / USART3_RTS / TIM1_CH2N' },
    { num: 28, name: 'PB15', type: 'gpio', desc: '通用I/O PB15', alt: 'SPI2_MOSI / TIM1_CH3N' },
    { num: 29, name: 'PA8', type: 'gpio', desc: '通用I/O PA8', alt: 'USART1_CK / TIM1_CH1 / MCO时钟输出' },
    { num: 30, name: 'PA9', type: 'gpio', desc: '通用I/O PA9', alt: 'USART1_TX / TIM1_CH2' },
    { num: 31, name: 'PA10', type: 'gpio', desc: '通用I/O PA10', alt: 'USART1_RX / TIM1_CH3' },
    { num: 32, name: 'PA11', type: 'gpio', desc: '通用I/O PA11', alt: 'USART1_CTS / CAN_RX / TIM1_CH4' },
    { num: 33, name: 'PA12', type: 'gpio', desc: '通用I/O PA12', alt: 'USART1_RTS / CAN_TX / TIM1_ETR' },
    { num: 34, name: 'PA13', type: 'jtag', desc: 'JTAG/SWD调试接口', alt: 'JTMS-SWDIO / 通用I/O PA13' },
    { num: 35, name: 'VSS_2', type: 'power', desc: '数字地 (I/O接地)', alt: '主数字电路接地引脚2' },
    { num: 36, name: 'VDD_2', type: 'power', desc: '数字电源 (2.0~3.6V)', alt: '主数字电路供电引脚2' },
    { num: 37, name: 'PA14', type: 'jtag', desc: 'JTAG/SWD调试接口', alt: 'JTCK-SWCLK / 通用I/O PA14' },
    { num: 38, name: 'PA15', type: 'jtag', desc: 'JTAG调试接口', alt: 'JTDI / 通用I/O PA15 / TIM2_CH1' },
    { num: 39, name: 'PB3', type: 'jtag', desc: 'JTAG调试接口', alt: 'JTDO / 通用I/O PB3 / TIM2_CH2' },
    { num: 40, name: 'PB4', type: 'jtag', desc: 'JTAG调试接口', alt: 'JNTRST / 通用I/O PB4 / TIM3_CH1' },
    { num: 41, name: 'PB5', type: 'gpio', desc: '通用I/O PB5', alt: 'I2C1_SMBA / TIM3_CH2' },
    { num: 42, name: 'PB6', type: 'gpio', desc: '通用I/O PB6', alt: 'I2C1_SCL / TIM4_CH1 / USART1_TX(重映射)' },
    { num: 43, name: 'PB7', type: 'gpio', desc: '通用I/O PB7', alt: 'I2C1_SDA / TIM4_CH2 / USART1_RX(重映射)' },
    { num: 44, name: 'BOOT0', type: 'boot', desc: '启动模式选择引脚0', alt: '高电平进入系统存储器Bootloader' },
    { num: 45, name: 'PB8', type: 'gpio', desc: '通用I/O PB8', alt: 'TIM4_CH3 / I2C1_SCL(重映射) / CAN_RX(重映射)' },
    { num: 46, name: 'PB9', type: 'gpio', desc: '通用I/O PB9', alt: 'TIM4_CH4 / I2C1_SDA(重映射) / CAN_TX(重映射)' },
    { num: 47, name: 'VSS_3', type: 'power', desc: '数字地 (I/O接地)', alt: '主数字电路接地引脚3' },
    { num: 48, name: 'VDD_3', type: 'power', desc: '数字电源 (2.0~3.6V)', alt: '主数字电路供电引脚3' },
];
>>>>>>> 53609b4b186f5c5178629d93f4e4c170b42854c9
